INSERT INTO TBROLE (NMROLE) VALUES ('ROLE_USER')
    ON CONFLICT (NMROLE) DO NOTHING;

INSERT INTO TBROLE (NMROLE) VALUES ('ROLE_ADMIN')
    ON CONFLICT (NMROLE) DO NOTHING;

INSERT INTO TBUSUARIO (NMUSUARIO, NMEMAIL, NMSENHA, FLATIVO)
VALUES ('Administrador', 'futmax@admin.com', '$2a$10$2mEpSiktdueKBjUl7Y7A.OkrBw.f/DKl4.OWxf796a5IdH8EwXkQq', true)
    ON CONFLICT (NMEMAIL) DO NOTHING;

INSERT INTO TBUSUARIOROLES (usuario_id, role_id)
SELECT u.cdUsuario, r.cdRole
FROM TBUSUARIO u, TBROLE r
WHERE u.NMEMAIL = 'futmax@admin.com' AND r.NMROLE = 'ROLE_ADMIN'
    ON CONFLICT DO NOTHING;
